#input data store and skims
store: NetworkData.h5
taz_skims_file: taz_skims.omx

tap_skims_files:
  - tap_skims_locl.omx
  - tap_skims_prem.omx

#number of households to simulate
households_sample_size: 1000



skim_time_periods:
    hours:
        - 0
        - 11
        - 16
        - 24
    labels:
        - AM
        - MD
        - PM


