
annotate_tables:
  - tablename: persons
    annotate:
      SPEC: annotate_persons
      DF: persons
      TABLES:
        - households
  - tablename: households
    annotate:
      SPEC: annotate_households
      DF: households
      TABLES:
        - persons
        - land_use
  - tablename: persons
    annotate:
      SPEC: annotate_persons_after_hh
      DF: persons
      TABLES:
        - households

# add the work and school location size tables for backwards compatibility if desired
add_size_tables: False