SAMPLE_SPEC: non_mandatory_tour_destination_sample.csv
SPEC: non_mandatory_tour_destination.csv
COEFFICIENTS: non_mandatory_tour_destination_coeffs.csv

SAMPLE_SIZE: 30

SIZE_TERM_SELECTOR: non_mandatory

# we can't use use household income_segment as this will also be set for non-workers
CHOOSER_SEGMENT_COLUMN_NAME: tour_type

# optional (comment out if not desired)
DEST_CHOICE_LOGSUM_COLUMN_NAME: destination_logsum

# comment out DEST_CHOICE_LOGSUM_COLUMN_NAME if no saved alt logsum table
DEST_CHOICE_SAMPLE_TABLE_NAME: tour_destination_sample


SEGMENTS:
  - shopping
  - othmaint
  - othdiscr
  - eatout
  - social
  - escort

SIMULATE_CHOOSER_COLUMNS:
  - tour_type
  - home_zone_id
  - person_id

LOGSUM_SETTINGS: tour_mode_choice.yaml

# model-specific logsum-related settings
CHOOSER_ORIG_COL_NAME: home_zone_id
ALT_DEST_COL_NAME: alt_dest
IN_PERIOD: 14
OUT_PERIOD: 14
