# input tables
input_table_list:
  - tablename: households
    filename: households.csv
    # The index column is set before keep_columns,
    # so don't put index in keep columns
    index_col: household_id
    recode_columns:
      home_zone_id: land_use.zone_id
    rename_columns:
      maz: home_zone_id
      np: hhsize
      nwrkrs_esr: num_workers
    keep_columns:
      - home_zone_id
      - hhsize
      - num_workers
      - hincp
      - hht
  - tablename: persons
    filename: persons.csv
    # The index column is set before keep_columns,
    # so don't put index in keep columns
    index_col: person_id
    rename_columns:
      maz: home_zone_id
      sporder: PNUM
    keep_columns:
      - household_id
      - home_zone_id
      - PNUM
      - agep
      - pecasOcc
      - sex
      - esr
      - wkw
      - wkhp
      - schg
  - tablename: land_use
    filename: land_use.csv
    # The index column is set before keep_columns,
    # so don't put index in keep columns
    index_col: zone_id
    recode_columns:
      zone_id: zero-based
    keep_columns:
      - retail
      - service
      - emp
      - pop
      - hshld
      - univ
      - acres
      - PARKTOT
      - PARKLNG
      - PROPFREE
      - PARKRATE
      - areatype
      - county
      - CBDFlag
      - N11
      - N21
      - N22
      - N23
      - N313233
      - N42
      - N4445
      - N4849
      - N51
      - N52
      - N53
      - N54
      - N55
      - N56
      - N61
      - N62
      - N71
      - N72
      - N81
      - N92
      - EnrollDS
      - EnrollPD
      - I_PCTLT10K
      - I_PCT10TO20
      - I_PCT20TO40
      - I_PCTGT40
      - RetailEmp30
      - PARKING_ZONE

# - shadow pricing global switches

# turn shadow_pricing on and off for all models (e.g. school and work)
# shadow pricing is deprecated for less than full samples
# use_shadow_pricing: True

# chunk_size:

# assume enough RAM to not chunk
chunk_training_mode: disabled

models:
  - initialize_landuse
  - initialize_households
  - compute_accessibility
  - school_location
  - workplace_location
  - auto_ownership_simulate
  - free_parking
  - cdap_simulate
  - mandatory_tour_frequency
  - mandatory_tour_scheduling
  - joint_tour_frequency
  - joint_tour_composition
  - joint_tour_participation
  - joint_tour_destination
  - joint_tour_scheduling
  - non_mandatory_tour_frequency
  - non_mandatory_tour_destination
  - non_mandatory_tour_scheduling
  - tour_mode_choice_simulate
  - atwork_subtour_frequency
  - atwork_subtour_destination
  - atwork_subtour_scheduling
  - atwork_subtour_mode_choice
  - stop_frequency
  - trip_purpose
  - trip_destination
  - trip_purpose_and_destination
  - trip_scheduling_choice
  - trip_departure_choice
  - trip_mode_choice
  - parking_location
  - write_data_dictionary
  - track_skim_usage
  - write_trip_matrices
  - write_tables

# resume_after:

multiprocess: False
fail_fast: True

multiprocess_steps:
  - name: mp_initialize_landuse
    begin: initialize_landuse
  - name: mp_accessibility
    begin: compute_accessibility
    num_processes: 5
    slice:
      tables:
        - accessibility
      # don't slice any tables not explicitly listed above in slice.tables
      exclude: True
  - name: mp_households
    begin: school_location
    num_processes: 5
    slice:
      tables:
        - households
        - persons
  - name: mp_summarize
    begin: write_tables


output_tables:
  h5_store: False
  action: include
  prefix: final_
  tables:
    - checkpoints
    - accessibility
    - tablename: land_use
      decode_columns:
        zone_id: land_use.zone_id
    - tablename: households
      decode_columns:
        home_zone_id: land_use.zone_id
    - tablename: persons
      decode_columns:
        home_zone_id: land_use.zone_id
        school_zone_id: nonnegative | land_use.zone_id
        workplace_zone_id: nonnegative | land_use.zone_id
    - tablename: tours
      decode_columns:
        origin: land_use.zone_id
        destination: land_use.zone_id
    - tablename: trips
      decode_columns:
        origin: land_use.zone_id
        destination: land_use.zone_id
    - joint_tour_participants

#trace_od: [100,10]
trace_hh_id:
# trace_hh_id: 2
#trace_hh_id: 1643904

min_value_of_time: 1
max_value_of_time: 50
distributed_vot_mu: 0.684
distributed_vot_sigma: 0.85

checkpoints: true
